system:
    domain: "social"
    host: "0.0.0.0"
    port: "8885"

mysql:
    userName: "root"
    mysqlPassword: "123456"
    dbName: "Social"
    dbHost: "mysql-svc"
    dbPort: "3306"

redis:
    redisHost: "redis-svc"
    redisPort: "6379"
    redisPassword: "123456"
    redisDbName: 0

rabbitmq:
    rabbitmqUserName: "root"
    rabbitmqPassword: "123456"
    rabbitmqHost: "rabbitmq-svc"
    rabbitmqPort: "5672"

etcd:
    etcdHost: "etcd-svc"
    etcdPort: "2379"
