linters-settings:
    # 禁用所有 lint 检查
    disable-all: true
    # 启用以下 lint 检查
    enable:
        - govet        # Go 编译器提供的简单代码检查工具
        - golint       # Go 代码规范检查工具
        - staticcheck  # 静态代码分析工具，用于发现更复杂的问题
        - unused       # 用于查找未使用的变量或导入包等
        - deadcode     # 用于检查未使用的代码，包括未使用的函数、变量、导入包等
        - ineffassign  # 用于检查未使用的变量赋值
        - errcheck     # 用于检查未处理的错误
        - gofmt        # 用于检查代码格式是否符合 Go 语言规范
        - structcheck  # 用于检查结构体字段的命名和使用是否规范
        - interfacer   # 用于检查接口的使用是否符合最佳实践
        - varcheck     # 用于检查全局变量的命名和使用是否规范

linters:
    # 禁用以下 lint 检查
    disable:
        - typecheck    # Go 编译器提供的类型检查工具
