apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es-storage
  hostPath:
    path: /data/elasticsearch
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: es-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
spec:
  storageClassName: es-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
spec:
  replicas: 1
  serviceName: es
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
          env:
            - name: "discovery.type"
              value: "single-node"
            - name: "ELASTIC_USERNAME"
              value: "elastic"
            - name: "ELASTIC_PASSWORD"
              value: "elastic"
          ports:
            - containerPort: 9200
          resources:
            limits:
              memory: "2Gi"
          volumeMounts:
            - name: es-pv
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-pv
          persistentVolumeClaim:
            claimName: es-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: es-svc
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30005
  type: NodePort
