// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "tiktok/cmd/api/biz/handler"
	"tiktok/cmd/api/biz/middleware"
	"tiktok/cmd/api/ws"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	//websocket
	r.GET("/ws", middleware.JWT(), ws.ServerWs)
}
