apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api-service
    template:
        metadata:
            labels:
                app: api-service
        spec:
            initContainers:
                -   name: check-skywalking
                    image: busybox
                    command:
                        - sh
                        - -c
                        - |
                            until nc -z -v skywalking-oap.skywalking 11800; do echo waiting for skywalking; sleep 2; done
            containers:
                - name: api-service
                  image: api_image:latest
                  imagePullPolicy: Never # 添加镜像拉取策略
                  ports:
                      - containerPort: 8881
                  command: ["sh", "-c", "./api"] # 添加启动命令
---
apiVersion: v1
kind: Service
metadata:
    name: api-service
spec:
    ports:
        - port: 8881
          targetPort: 8881
    selector:
        app: api-service
