apiVersion: apps/v1
kind: Deployment
metadata:
    name: interaction-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: interaction-service
    template:
        metadata:
            labels:
                app: interaction-service
        spec:
            initContainers:
                -   name: check-skywalking
                    image: busybox
                    command:
                        - sh
                        - -c
                        - |
                            until nc -z -v skywalking-oap.skywalking 11800; do echo waiting for skywalking; sleep 2; done
            containers:
                - name: interaction-service
                  image: interaction_image:latest
                  imagePullPolicy: Never # 添加镜像拉取策略
                  ports:
                      - containerPort: 8884
                  command: ["sh", "-c", "./interaction"] # 添加启动命令
---
apiVersion: v1
kind: Service
metadata:
    name: interaction-service
spec:
    ports:
        - port: 8884
          targetPort: 8884
    selector:
        app: interaction-service
