apiVersion: apps/v1
kind: Deployment
metadata:
    name: social-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: social-service
    template:
        metadata:
            labels:
                app: social-service
        spec:
            initContainers:
                -   name: check-skywalking
                    image: busybox
                    command:
                        - sh
                        - -c
                        - |
                            until nc -z -v skywalking-oap.skywalking 11800; do echo waiting for skywalking; sleep 2; done
            containers:
                - name: social-service
                  image: social_image:latest
                  imagePullPolicy: Never # 添加镜像拉取策略
                  ports:
                      - containerPort: 8885
                  command: ["sh", "-c", "cd cmd/social && ./social"] # 添加启动命令
---
apiVersion: v1
kind: Service
metadata:
    name: social-service
spec:
    ports:
        - port: 8885
          targetPort: 8885
    selector:
        app: social-service
