apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user-service
    template:
        metadata:
            labels:
                app: user-service
        spec:
            initContainers:
                - name: check-skywalking
                  image: busybox
                  command:
                      - sh
                      - -c
                      - |
                          until nc -z -v skywalking-oap.skywalking 11800; do echo waiting for skywalking; sleep 2; done
            containers:
                - name: user-service
                  image: user_image:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8882
                      - containerPort: 6060
                  command: ["sh", "-c", "./user"]
---
apiVersion: v1
kind: Service
metadata:
    name: user-service
spec:
    ports:
        - name: http
          port: 8882
          targetPort: 8882
        - name: pprof
          port: 6060
          targetPort: 6060
    selector:
        app: user-service
