apiVersion: apps/v1
kind: Deployment
metadata:
    name: video-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: video-service
    template:
        metadata:
            labels:
                app: video-service
        spec:
            initContainers:
                -   name: check-skywalking
                    image: busybox
                    command:
                        - sh
                        - -c
                        - |
                            until nc -z -v skywalking-oap.skywalking 11800; do echo waiting for skywalking; sleep 2; done
            containers:
                - name: video-service
                  image: video_image:latest
                  imagePullPolicy: Never # 添加镜像拉取策略
                  ports:
                      - containerPort: 8883
                      - containerPort: 6060
                  command: ["sh", "-c", "cd cmd/video && ./video"] # 添加启动命令
---
apiVersion: v1
kind: Service
metadata:
    name: video-service
spec:
    ports:
        - name: http
          port: 8883
          targetPort: 8883
        - name: pprof
          port: 6060
          targetPort: 6060
    selector:
        app: video-service

