apiVersion: apps/v1
kind: Deployment
metadata:
    name: video-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: video-service
    template:
        metadata:
            labels:
                app: video-service
        spec:
            containers:
                - name: video-service
                  image: video_image:latest
                  imagePullPolicy: Never # 添加镜像拉取策略
                  ports:
                      - containerPort: 8883
                  command: ["sh", "-c", "cd cmd/video && ./video"] # 添加启动命令
---
apiVersion: v1
kind: Service
metadata:
    name: video-service
spec:
    ports:
        - port: 8883
          targetPort: 8883
    selector:
        app: video-service
