// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
	"tiktok/cmd/api/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tiktokMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _mfaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfabindMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmfaqrcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinfoMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avataruploadMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _popularlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _deletecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentpublishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _fanslistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _friendsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendslistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _like0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}
