system:
    domain: "video"
    host: "0.0.0.0"
    port: "8883"

mysql:
    userName: "root"
    mysqlPassword: "123456"
    dbName: "Video"
    dbHost: "mysql-svc"
    dbPort: "3306"

redis:
    redisHost: "redis-svc"
    redisPort: "6379"
    redisPassword: "123456"
    redisDbName: 0

oss:
    OSS_END_POINT: ""
    OSS_ACCESS_KEY_ID: ""
    OSS_ACCESS_KEY_SECRET: ""
    OSS_BUCKET: ""

es:
    esUserName: "elastic"
    esPassword: "123456"
    esHost: "es-svc"
    esPort: "9200"

rabbitmq:
    rabbitmqUserName: "root"
    rabbitmqPassword: "123456"
    rabbitmqHost: "rabbitmq-svc"
    rabbitmqPort: "5672"

etcd:
    etcdHost: "etcd-svc"
    etcdPort: "2379"
