// Code generated by Kitex v0.9.0. DO NOT EDIT.

package socialservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	social "tiktok/kitex_gen/social"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Follow(ctx context.Context, req *social.FollowRequest, callOptions ...callopt.Option) (r *social.FollowResponse, err error)
	FollowList(ctx context.Context, req *social.FollowListRequest, callOptions ...callopt.Option) (r *social.FollowListResponse, err error)
	FansList(ctx context.Context, req *social.FansListRequest, callOptions ...callopt.Option) (r *social.FansListResponse, err error)
	FriendsList(ctx context.Context, req *social.FriendsListRequest, callOptions ...callopt.Option) (r *social.FriendsListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kSocialServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSocialServiceClient struct {
	*kClient
}

func (p *kSocialServiceClient) Follow(ctx context.Context, req *social.FollowRequest, callOptions ...callopt.Option) (r *social.FollowResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Follow(ctx, req)
}

func (p *kSocialServiceClient) FollowList(ctx context.Context, req *social.FollowListRequest, callOptions ...callopt.Option) (r *social.FollowListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowList(ctx, req)
}

func (p *kSocialServiceClient) FansList(ctx context.Context, req *social.FansListRequest, callOptions ...callopt.Option) (r *social.FansListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FansList(ctx, req)
}

func (p *kSocialServiceClient) FriendsList(ctx context.Context, req *social.FriendsListRequest, callOptions ...callopt.Option) (r *social.FriendsListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendsList(ctx, req)
}
