apiVersion: v1
kind: Pod
metadata:
  name: network-tools
spec:
  containers:
    - name: network-tools
      image: alpine:latest
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      tty: true
      stdin: true
      securityContext:
        runAsUser: 0
      imagePullPolicy: IfNotPresent
