system:
    domain: "api"
    host: "0.0.0.0"
    port: "8881"

rabbitmq:
    rabbitmqUserName: "root"
    rabbitmqPassword: "123456"
    rabbitmqHost: "rabbitmq-svc"
    rabbitmqPort: "5672"

etcd:
    etcdHost: "etcd-svc"
    etcdPort: "2379"
